# Generated by Django 5.0.2 on 2024-03-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='noreply@example.com', max_length=60),
            preserve_default=False,
        ),
    ]
