# Generated by Django 5.0.6 on 2024-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_curso_datafimcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.CharField(default='null', max_length=80),
            preserve_default=False,
        ),
    ]
